#!/bin/sh
# This file is part of DerridAI, a cELF-compliant research workspace
# Copyright © 2026  Aaron John Schlosser, PhD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Enabled by scripts/install-git-hooks.sh (core.hooksPath). Skip with DERRIDAI_SKIP_PREFLIGHT=1.
[ "${DERRIDAI_SKIP_PREFLIGHT:-}" = "1" ] && exit 0
# A push containing only remote-branch deletions needs no preflight.
needs_preflight=0
while read -r _ local_sha _ _; do
  [ "$local_sha" != "0000000000000000000000000000000000000000" ] && needs_preflight=1
done
[ "$needs_preflight" = 0 ] && exit 0
exec "$(git rev-parse --show-toplevel)/scripts/preflight.sh"
