/* Copyright 2026 Aaron John Schlosser, PhD. */
import { bindJobsState } from "../state/jobsState";
import {
  bindSharedState,
  compareState,
  corpusState,
  searchState,
  vectorState,
  worksState,
} from "../state/workspaceState";

// Initial value of the legacy runtime's single mutable workspace state. Moved verbatim from
// runtime.js so the shape has one home; the runtime still owns the instance it creates.

export function createRuntimeState() {
  const state = {
    userContext: null,
    view: "home",
    selected: {},
    searches: {},
    listFilters: {},
    pages: {},
    pageSize: 100,
    sorts: {},
    researcherRecordId: "",
    researcherCompareA: "",
    researcherCompareB: "",
    annotationView: "works",
    annotationSearch: "",
    serverAnnotations: [],
    serverAnnotationsStore: "",
    annotationsFetchedAt: 0,
    dashboardMetricIndex: 0,
    lastViewedRecord: null,
    foregroundUpsertCancelRequested: false,
    recordFind: "",
    recordFindKey: "",
    pdf: {
      doc: null,
      file: null,
      url: "",
      name: "",
      title: "",
      author: "",
      page: 1,
      rotation: 0,
      text: "",
      search: "",
      relatedSearch: "",
      extractError: "",
      extractionSource: "",
    },
    health: null,
    llmStatus: null,
    reviewSelection: new Set(),
    selectedEvidence: {},
    researcherProviderProfiles: [],
    translations: { locale: "en-US", dictionary: {}, base: {} },
    navHistory: [],
    navForward: [],
    sidebarCollapsed: false,
    collectionsCollapsed: false,
    operationToastsMinimized: false,
    operationStackPosition: null,
    collapsedPanels: {},
    providerStatuses: {},
    providerWarmups: {},
    tableColumns: {},
    upsertState: {},
    upsertIgnored: {},
    operationProgress: {},
    jobsPollTimer: null,
    foregroundUpsertActive: false,
    warmup: { status: "idle", message: "" },
    faqSearch: "",
    faqPage: 1,
    faqExpanded: {},
    ragConfig: {
      source_collection: "",
      locales: ["en", "fr"],
      search_types: ["similarity", "lexical", "mmr"],
      k: 64,
      fetch_k: 500,
      lambda_mult: 0.7,
      rrf_k: 60,
      rerank_top_n: 24,
      reranker: "cross_encoder",
      cross_encoder_model: "cross-encoder/ms-marco-MiniLM-L-6-v2",
      query_decomposition: true,
      query_decomposition_num_predict: 768,
      response_language: "auto",
      evidence_record_char_limit: 12000,
      evidence_total_char_limit: 120000,
      bind_citations: true,
      include_works_cited: true,
      auto_grade: false,
      auto_grade_provider_profile_id: "",
      provider_profile_id: "",
      skip_retrieval: false,
      use_prior_response_memory: false,
      use_prior_claim_memory: false,
      memory_profile_id: "",
      prompt: "",
      instructions: "",
      history: [],
      run_history: [],
    },
    appConfig: {
      chat_provider: "ollama",
      chat_model: "gemma4:e2b",
      embedding_provider: "ollama",
      embedding_model: "bge-m3:latest",
      ollama_base_url: "http://host.docker.internal:11434",
      ollama_rag_concurrency: 1,
      openai_base_url: "http://host.docker.internal:3001/v1",
      openai_model: "auto",
      openai_model_mode: "auto",
      openai_model_kind: "any",
      openai_api_key: "",
      default_review_preset: "text",
      default_llm_run_mode: "foreground",
      desktop_notifications: false,
      ui_color_theme: "green",
      ui_color_scheme: "system",
      ui_contrast: "system",
      default_provider_profile: "",
      // Loading a model takes memory and time, and evicts whichever model is in use, so it is not done until asked for.
      warm_default_provider_on_start: false,
      review_provider_profile: "",
      provider_profiles: [],
      background_llm: true,
      openai_num_predict: 4096,
      openai_temperature: 0,
      openai_top_p: 1,
      openai_seed: "",
      openai_extra_options: "{}",
      metadata_num_predict: 768,
      text_num_predict: 4096,
    },
    llmConfig: {
      model: "gemma4:e2b",
      num_ctx: 16384,
      num_predict: "",
      think: "false",
      temperature: 0,
      top_k: 0,
      top_p: 1,
      min_p: "",
      repeat_penalty: 1.1,
      seed: "",
      mirostat: 0,
      mirostat_eta: "",
      mirostat_tau: "",
      keep_alive: "10m",
      extra_options: "{}",
    },
    storageReady: false,
  };
  // Background-job and per-view workspace fields live in stores shared with Vue code; see state/jobsState.ts and
  // state/workspaceState.ts.
  const withJobs = bindJobsState(state);
  const withVector = bindSharedState(withJobs, vectorState);
  const withCompare = bindSharedState(withVector, compareState);
  const withSearch = bindSharedState(withCompare, searchState);
  const withWorks = bindSharedState(withSearch, worksState);
  return bindSharedState(withWorks, corpusState);
}

export type RuntimeState = ReturnType<typeof createRuntimeState>;
