# Copyright 2026 Aaron John Schlosser, PhD.
"""Normative DERRIDAI 1.0 object and relationship registry.

The registry describes semantic object types and walkable relationships. It is
presentation-neutral: the API and frontend use it to explain cardinality and
inverse relations without hard-coding an ontology a second time.
"""
from __future__ import annotations

from typing import Any

OBJECT_TYPES: tuple[dict[str, Any], ...] = (
    {"type": "SourceDocument", "profile": "Core", "persistence": "durable", "label": "Source document"},
    {"type": "SourceSpan", "profile": "Core", "persistence": "durable_locator", "label": "Source span"},
    {"type": "Record", "profile": "Core", "persistence": "durable", "label": "Record"},
    {"type": "RecordRevision", "profile": "Core", "persistence": "durable_versioned", "label": "Record revision"},
    {"type": "FieldAssertion", "profile": "Core", "persistence": "durable_when_retained", "label": "Field assertion"},
    {"type": "CorpusPublication", "profile": "Publication", "persistence": "durable_immutable", "label": "Corpus publication"},
    {"type": "RetrievalRun", "profile": "Retrieval", "persistence": "run_audit", "label": "Retrieval run"},
    {"type": "EvidenceRef", "profile": "Evidence", "persistence": "durable_for_audit", "label": "Evidence reference"},
    {"type": "EvidencePacket", "profile": "Evidence", "persistence": "run_audit", "label": "Evidence packet"},
    {"type": "GenerationRun", "profile": "Claim-Binding", "persistence": "run_audit", "label": "Generation run"},
    {"type": "GeneratedClaim", "profile": "Claim-Binding", "persistence": "run_audit", "label": "Generated claim"},
    {"type": "SupportBinding", "profile": "Claim-Binding", "persistence": "run_audit", "label": "Support binding"},
    {"type": "ResearchRun", "profile": "Reproducible Research", "persistence": "run_audit", "label": "Research run"},
)

RELATIONSHIPS: tuple[dict[str, Any], ...] = (
    {"id": "source_document_spans", "source_type": "SourceDocument", "target_type": "SourceSpan", "relation": "contains span", "inverse_relation": "belongs to document", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Core"},
    {"id": "source_document_records", "source_type": "SourceDocument", "target_type": "Record", "relation": "contains record", "inverse_relation": "belongs to document", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Core"},
    {"id": "record_spans", "source_type": "Record", "target_type": "SourceSpan", "relation": "derives from", "inverse_relation": "contributes to", "source_cardinality": "1..*", "target_cardinality": "0..*", "profile": "Core"},
    {"id": "record_revisions", "source_type": "Record", "target_type": "RecordRevision", "relation": "has revision", "inverse_relation": "revision of", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Core"},
    {"id": "record_assertions", "source_type": "Record", "target_type": "FieldAssertion", "relation": "has assertion", "inverse_relation": "assertion in context of", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Core"},
    {"id": "revision_assertions", "source_type": "RecordRevision", "target_type": "FieldAssertion", "relation": "has assertion", "inverse_relation": "assertion at revision", "source_cardinality": "0..*", "target_cardinality": "0..1", "profile": "Core"},
    {"id": "publication_records", "source_type": "CorpusPublication", "target_type": "Record", "relation": "publishes", "inverse_relation": "published in", "source_cardinality": "1..*", "target_cardinality": "0..*", "profile": "Publication"},
    {"id": "retrieval_evidence", "source_type": "RetrievalRun", "target_type": "EvidenceRef", "relation": "may acquire", "inverse_relation": "acquired by", "source_cardinality": "0..*", "target_cardinality": "0..*", "profile": "Retrieval"},
    {"id": "packet_evidence", "source_type": "EvidencePacket", "target_type": "EvidenceRef", "relation": "contains reference", "inverse_relation": "included in packet", "source_cardinality": "0..*", "target_cardinality": "0..*", "profile": "Evidence"},
    {"id": "generation_packet", "source_type": "GenerationRun", "target_type": "EvidencePacket", "relation": "uses", "inverse_relation": "used by", "source_cardinality": "0..1", "target_cardinality": "0..*", "profile": "Claim-Binding"},
    {"id": "generation_claims", "source_type": "GenerationRun", "target_type": "GeneratedClaim", "relation": "produces", "inverse_relation": "generated by", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Claim-Binding"},
    {"id": "claim_bindings", "source_type": "GeneratedClaim", "target_type": "SupportBinding", "relation": "has support binding", "inverse_relation": "binds claim", "source_cardinality": "0..*", "target_cardinality": "1", "profile": "Claim-Binding"},
    {"id": "binding_evidence", "source_type": "SupportBinding", "target_type": "EvidenceRef", "relation": "binds evidence", "inverse_relation": "bound by", "source_cardinality": "1..*", "target_cardinality": "0..*", "profile": "Claim-Binding"},
    {"id": "research_publications", "source_type": "ResearchRun", "target_type": "CorpusPublication", "relation": "references publication", "inverse_relation": "used by research run", "source_cardinality": "0..*", "target_cardinality": "0..*", "profile": "Reproducible Research"},
    {"id": "research_packets", "source_type": "ResearchRun", "target_type": "EvidencePacket", "relation": "references evidence packet", "inverse_relation": "used by research run", "source_cardinality": "0..*", "target_cardinality": "0..*", "profile": "Reproducible Research"},
    {"id": "research_generations", "source_type": "ResearchRun", "target_type": "GenerationRun", "relation": "references generation", "inverse_relation": "part of research run", "source_cardinality": "0..*", "target_cardinality": "0..1", "profile": "Reproducible Research"},
)


def normative_model() -> dict[str, Any]:
    """Return the stable type-level graph used by model exploration UIs."""
    return {
        "specification_version": "1.0",
        "nodes": [dict(item, normative=True) for item in OBJECT_TYPES],
        "edges": [dict(item, normative=True) for item in RELATIONSHIPS],
    }


def relationship_for(source_type: str, target_type: str) -> dict[str, Any] | None:
    """Resolve direct or inverse registry metadata for one instance edge."""
    for item in RELATIONSHIPS:
        if item["source_type"] == source_type and item["target_type"] == target_type:
            return dict(item, inverse=False, normative=True)
        if item["source_type"] == target_type and item["target_type"] == source_type:
            return {
                **item,
                "relation": item["inverse_relation"],
                "inverse_relation": item["relation"],
                "source_cardinality": item["target_cardinality"],
                "target_cardinality": item["source_cardinality"],
                "inverse": True,
                "normative": True,
            }
    return None
