# This file is part of DerridAI, a cELF-compliant research workspace
# Copyright © 2026  Aaron John Schlosser, PhD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Pinned publication-time embeddings matching the static site's browser default.

The static site uses a quantized multilingual E5 model for query embeddings. When an
administrator chooses the recommended publication strategy, DerridAI embeds the
published Record texts with the same pinned model artifact and vector-changing
contract before packaging the site. The model is derived infrastructure: it is
downloaded only for an explicit publication request, cached outside canonical corpus
state, and never changes a Record.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any, Sequence

from .config import settings

MODEL_ID = "Xenova/multilingual-e5-small"
MODEL_REVISION = "761b726dd34fb83930e26aab4e9ac3899aa1fa78"
MODEL_FILE = "onnx/model_quantized.onnx"
TOKENIZER_FILE = "tokenizer.json"
MODEL_FILE_BYTES = 118_308_185
TOKENIZER_FILE_BYTES = 17_082_730
MODEL_FILE_SHA256 = "f80102d3f2a1229f387d3c81909990d8945513e347b0eab049f7de3c6f98c193"
TOKENIZER_FILE_SHA256 = "0b44a9d7b51c3c62626640cda0e2c2f70fdacdc25bbbd68038369d14ebdf4c39"
DIMENSION = 384
MAX_LENGTH = 512
DTYPE = "q8"
POOLING = "mean"
NORMALIZE = True
QUERY_PREFIX = "query: "
DOCUMENT_PREFIX = "passage: "
# Must match the descriptor generated by api/app/site_assets/derridai-site.js.
VARIANT = (
    "query-prefix=query: ;document-prefix=passage: ;"
    "dtype=q8;pooling=mean;normalize=true"
)
DOWNLOAD_BYTES = MODEL_FILE_BYTES + TOKENIZER_FILE_BYTES


def cache_dir() -> Path:
    """Model cache used only for derived publication/browser embedding infrastructure."""
    return Path(settings.chroma_data_root) / "publication_embedder"


def contract() -> dict[str, Any]:
    """Exact vector contract written into a recommended static-site publication."""
    return {
        "provider": "transformers",
        "model": MODEL_ID,
        "revision": MODEL_REVISION,
        "variant": VARIANT,
        "dimension": DIMENSION,
        "distance_metric": "cosine",
        "text_field": "text",
    }


def _cached(filename: str) -> str | None:
    try:
        from huggingface_hub import try_to_load_from_cache

        path = try_to_load_from_cache(
            MODEL_ID,
            filename,
            revision=MODEL_REVISION,
            cache_dir=str(cache_dir()),
        )
    except Exception:
        return None
    return path if isinstance(path, str) else None


def runtime_info() -> dict[str, Any]:
    """Small administrator-facing description; does not download anything."""
    return {
        "model": MODEL_ID,
        "revision": MODEL_REVISION,
        "dimension": DIMENSION,
        "cached": bool(_cached(MODEL_FILE) and _cached(TOKENIZER_FILE)),
        "download_bytes": DOWNLOAD_BYTES,
    }


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _verified_download(filename: str, *, size: int, sha256: str) -> Path:
    """Download one pinned Hub artifact and verify the immutable large-file contract."""
    from huggingface_hub import hf_hub_download

    path = Path(
        hf_hub_download(
            repo_id=MODEL_ID,
            filename=filename,
            revision=MODEL_REVISION,
            cache_dir=str(cache_dir()),
        )
    )
    if path.stat().st_size != size or _sha256(path) != sha256:
        raise RuntimeError(f"Publication embedding artifact failed verification: {filename}.")
    return path


def _model_files() -> tuple[Path, Path]:
    model = _verified_download(
        MODEL_FILE,
        size=MODEL_FILE_BYTES,
        sha256=MODEL_FILE_SHA256,
    )
    tokenizer = _verified_download(
        TOKENIZER_FILE,
        size=TOKENIZER_FILE_BYTES,
        sha256=TOKENIZER_FILE_SHA256,
    )
    return model, tokenizer


def embed_records(
    records: Sequence[dict[str, Any]],
    *,
    batch_size: int = 8,
) -> list[list[float] | None]:
    """Embed Record text with the browser-default E5 passage contract.

    Empty text keeps a None vector so publication chunk identity remains aligned
    with the Record list. The model's token embeddings are attention-mask mean pooled
    and L2-normalized exactly as the browser profile specifies.
    """
    import numpy as np
    import onnxruntime as ort
    from transformers import AutoTokenizer

    model_path, _tokenizer_path = _model_files()
    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_ID,
        revision=MODEL_REVISION,
        cache_dir=str(cache_dir()),
        local_files_only=True,
    )
    session = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    input_names = {item.name for item in session.get_inputs()}
    result: list[list[float] | None] = [None] * len(records)
    indexed = [
        (index, f"{DOCUMENT_PREFIX}{str(record.get('text') or '').strip()}")
        for index, record in enumerate(records)
        if str(record.get("text") or "").strip()
    ]
    batch_size = max(1, min(int(batch_size), 64))

    for start in range(0, len(indexed), batch_size):
        batch = indexed[start : start + batch_size]
        encoded = tokenizer(
            [text for _index, text in batch],
            padding=True,
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors="np",
        )
        inputs = {
            name: np.asarray(value, dtype=np.int64)
            for name, value in encoded.items()
            if name in input_names
        }
        output = np.asarray(session.run(None, inputs)[0], dtype=np.float32)
        if output.ndim == 3:
            mask = np.asarray(encoded["attention_mask"], dtype=np.float32)[..., None]
            summed = (output * mask).sum(axis=1)
            counts = np.clip(mask.sum(axis=1), 1.0, None)
            output = summed / counts
        if output.ndim != 2 or output.shape[1] != DIMENSION:
            raise RuntimeError(
                f"Publication embedding model returned {tuple(output.shape)}; "
                f"expected (*, {DIMENSION})."
            )
        norms = np.linalg.norm(output, axis=1, keepdims=True)
        output = output / np.clip(norms, 1e-12, None)
        for (record_index, _text), vector in zip(batch, output, strict=True):
            result[record_index] = [float(value) for value in vector]

    return result
