/* Copyright 2026 Aaron John Schlosser, PhD. */

// Static tables used by the legacy runtime, moved verbatim.

export const FIELD_LABELS = {
  record_id: "Record ID",
  work: "Work",
  document_author: "Document author",
  edition: "Edition",
  year: "Year",
  page_start: "Page start",
  page_end: "Page end",
  region_type: "Region type",
  region_author: "Region author",
  primary_text: "Primary text",
  canonical_work_id: "Canonical work ID",
  speaker: "Speaker",
  position_holder: "Position holder",
  target: "Target",
  discourse_role: "Discourse role",
  proposition_status: "Proposition status",
  semantic_function: "Semantic function",
  stance: "Stance",
  claim_scope: "Claim scope",
  is_direct_quote: "Direct quote",
  quoted_speaker: "Quoted speaker",
  quoted_author: "Quoted author",
  quoted_work: "Quoted work",
  quoted_position_holder: "Quoted position holder",
  quoted_addressee: "Quoted addressee",
  quoted_referent: "Quoted referent",
  quotation_chain: "Quotation chain",
  topics: "Topics",
  concepts: "Concepts",
  persons: "Persons",
  works_referenced: "Works referenced",
  attribution_confidence: "Attribution confidence",
  semantic_classification_confidence: "Semantic classification confidence",
  extraction_quality: "Extraction quality",
  needs_review: "Needs review",
  review_reason: "Review reason",
  document_language: "Document language",
  original_language: "Original language",
  document_is_translation: "Document is translation",
  translator: "Translator",
  publisher: "Publisher",
  publication_year: "Publication year",
  publication_place: "Publication place",
  isbn: "ISBN",
  document_title: "Document title",
  short_title: "Short title",
  original_title: "Original title",
  cover_url: "Cover URL",
  inline_citation: "Inline citation",
  full_citation: "Full citation",
  text: "Extracted text",
  text_length: "Text length",
  updates: "Change history",
  pdf_file: "PDF file",
  pdf_page: "PDF page",
  pdf_pages: "PDF pages",
  pdf_links: "PDF links",
  __file: "File",
  __db_status: "DB status",
  _chroma_id: "Chroma ID",
};

export const viewConfig = [
  { id: "home", label: "Home", icon: "dashboard", section: "Overview" },
  { id: "list", label: "Records", icon: "list", section: "Corpus" },
  { id: "record", label: "Record View", icon: "record", section: "Corpus" },
  { id: "works", label: "Works", icon: "books", section: "Corpus" },
  { id: "global", label: "Search", icon: "search", section: "Corpus" },
  { id: "annotations", label: "Annotations", icon: "record", section: "Corpus" },
  { id: "pdf", label: "Corpus Builder", icon: "pdf", section: "Tools" },
  { id: "compare", label: "Compare", icon: "compare", section: "Tools" },
  { id: "vector", label: "Vector Stores", icon: "database", section: "Tools" },
  { id: "rag", label: "Research", icon: "spark", section: "Research" },
  { id: "faq", label: "Response Library", icon: "books", section: "Research" },
  { id: "responsecache", label: "Response Cache", icon: "database", section: "Research" },
  { id: "providers", label: "LLM Providers", icon: "spark", section: "System" },
  { id: "config", label: "Settings", icon: "gear", section: "System" },
];

export const TABLE_DEFAULTS = {
  // Record actions are rendered as a dedicated trailing column. Keep the default
  // data columns compact enough to scan on a laptop and let users opt into the
  // rest through the column chooser.
  list: ["__db_status", "work", "page_start", "needs_review", "text"],
  global: ["__db_status", "work", "page_start", "needs_review", "text"],
  vector: ["_chroma_id", "record_id", "work", "page_start", "speaker", "needs_review"],
};

export const SEARCH_LOADED_COLUMNS = ["__db_status", "work", "page_start", "needs_review", "text"];
