/*
 * This file is part of DerridAI, a cELF-compliant research workspace
 * Copyright © 2026  Aaron John Schlosser, PhD
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Typed access to the served pipeline catalog contract for stories and tests.
// The JSON is generated by scripts/export_pipeline_catalog_fixture.py; run it after
// changing a purpose, strategy or vocabulary (tests/test_pipeline_catalog_fixture.py fails until then).
import contract from "./pipelineCatalogContract.json";
import type {
  PipelineContractIdentity,
  PipelinePurpose,
  PipelineStrategy,
  PipelineWorkflowVocabulary,
} from "../../../types/pipelines";

export const contractIdentity = contract.contract as unknown as PipelineContractIdentity;
export const contractPurposes = contract.purposes as unknown as PipelinePurpose[];
export const contractVocabulary = contract.vocabulary as unknown as PipelineWorkflowVocabulary;
export const contractStrategies = contract.strategies as unknown as PipelineStrategy[];

export function contractStrategy(strategyId: string): PipelineStrategy {
  const strategy = contractStrategies.find((item) => item.strategy_id === strategyId);
  if (!strategy) throw new Error(`Unknown strategy in catalog contract: ${strategyId}`);
  return strategy;
}

export function contractPurpose(purposeId: string): PipelinePurpose {
  const purpose = contractPurposes.find((item) => item.purpose_id === purposeId);
  if (!purpose) throw new Error(`Unknown purpose in catalog contract: ${purposeId}`);
  return purpose;
}
