import type { Meta, StoryObj } from "@storybook/vue3-vite";
import CorpusMetadataResolutionPanel from "./CorpusMetadataResolutionPanel.vue";
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- SA-16: intentionally sparse Storybook fixture exercises partial/loading data without fabricating unrelated fields.
const record:any={record_id:"record-00018",record_revision:3,text:"A passage of primary text.",source_block_ids:["p032-b001"],pdf_pages:[32],page_start:32,page_end:32,needs_review:true,accepted:false,review_disposition:"pending",metadata_complete:false,metadata_incomplete_fields:["region_type","discourse_role"],metadata_review_fields:["region_type","discourse_role"],metadata_field_status:{region_type:{status:"unresolved",method:"llm",reason:"Deterministic and model classifications disagreed.",confidence:.62},discourse_role:{status:"unresolved",method:"llm",reason:"Available source evidence is ambiguous.",confidence:.58}}};
const meta={title:"Corpus Builder/Review/Metadata Resolution",component:CorpusMetadataResolutionPanel,args:{record,regionTypes:["main_text","front_matter","back_matter","footnote"],discourseRoles:["assertion","analysis","quotation","reported_position","critique","transition"]}} satisfies Meta<typeof CorpusMetadataResolutionPanel>;
export default meta; type Story=StoryObj<typeof meta>;
export const AmbiguousFields:Story={};
export const Resolved:Story={args:{record:{...record,metadata_complete:true,metadata_incomplete_fields:[],metadata_field_status:{region_type:{status:"human_confirmed",method:"human"},discourse_role:{status:"human_confirmed",method:"human"}}}}};

export const LlmProposalsReadyForConfirmation:Story={args:{record:{...record,metadata_complete:true,metadata_incomplete_fields:[],metadata_review_fields:[],region_type:"main_text",primary_text:true,discourse_role:"analysis",position_holder:"Jacques Derrida",metadata_field_status:{region_type:{status:"model_inferred",method:"llm",confidence:.97,reason:"Substantive body text."},primary_text:{status:"model_inferred",method:"llm",confidence:.98,reason:"Part of the work proper."},discourse_role:{status:"model_inferred",method:"llm",confidence:.91,reason:"Analytical exposition."},position_holder:{status:"model_inferred",method:"llm",confidence:.88,reason:"The proposition is attributed to Derrida."}}}}};

export const PrimaryTextHumanDecisionNo:Story={args:{record:{...record,metadata_complete:false,metadata_incomplete_fields:["primary_text"],metadata_review_fields:["primary_text"],primary_text:null,metadata_field_status:{primary_text:{status:"unresolved",method:"llm",confidence:.54,reason:"The passage appears to be editorial apparatus, but the source boundary is ambiguous."}}}}};
export const InheritedAndOverriddenBibliography:Story={args:{record:{...record,work:"On Cosmopolitanism and Forgiveness",document_title:"On Cosmopolitanism and Forgiveness",document_author:"Jacques Derrida",translator:"Mark Dooley and Michael Hughes",publisher:"Routledge",publication_year:2001,metadata_incomplete_fields:[],metadata_review_fields:[],metadata_field_status:{work:{status:"inherited",method:"document_manifest",confidence:1},document_title:{status:"inherited",method:"document_manifest",confidence:1},document_author:{status:"human_override",method:"human_record_override",confidence:1,reason:"This record deliberately overrides document-level metadata."},translator:{status:"inherited",method:"document_manifest",confidence:1},publisher:{status:"inherited",method:"document_manifest",confidence:1},publication_year:{status:"inherited",method:"document_manifest",confidence:1}}}}};
export const FrenchLengthStress:Story={args:{record:{...record,document_title:"Cosmopolites de tous les pays, encore un effort ! — édition critique annotée",document_author:"Jacques Derrida",translator:"Traduction, révision et appareil critique particulièrement détaillés",metadata_incomplete_fields:[],metadata_review_fields:[],metadata_field_status:{document_title:{status:"inherited",method:"document_manifest",confidence:1},document_author:{status:"inherited",method:"document_manifest",confidence:1},translator:{status:"human_override",method:"human_record_override",confidence:1}}}}};
