<script setup lang="ts">
import { computed } from 'vue';
import { useI18nStore } from '../stores/i18n';
const props=defineProps<{issues?:Array<Record<string,unknown>>;resolved?:boolean}>();
const i18n=useI18nStore();
const rows=computed(()=>props.issues||[]);
function pages(issue:Record<string,unknown>){return Array.isArray(issue.pages)?issue.pages.join(', '):'—'}
function label(issue:Record<string,unknown>){const code=String(issue.code||'source_quality');return i18n.t(`pdf_corpus.source_issue.${code}`,code==='fragmented_glyph_layout'?'Fragmented text layout':code==='source_quality_blocking'?'Damaged PDF text layer':'Source extraction issue')}
</script>
<template><section v-if="rows.length" class="source-issues" :data-resolved="resolved?'true':'false'" role="note"><header><div><b>{{resolved?i18n.t('pdf_corpus.source_issue_resolved','Resolved source issue'):i18n.t('pdf_corpus.source_issue_title','Source extraction issue')}}</b><span>{{resolved?i18n.t('pdf_corpus.source_issue_resolved_help','The reviewer corrected the corpus text; the original extraction remains preserved for audit.'):i18n.t('pdf_corpus.source_issue_help','Inspect the affected source and decide whether to correct the record text or rebuild/re-extract the PDF source.')}}</span></div></header><article v-for="(issue,index) in rows" :key="`${issue.code||'issue'}-${index}`"><div><strong>{{label(issue)}}</strong><span><span class="severity">{{i18n.t(`pdf_corpus.source_severity.${String(issue.severity||'warning')}`,String(issue.severity||'warning'))}}</span> · {{i18n.t('pdf_corpus.pages','pp.')}} {{pages(issue)}}</span></div><p>{{String(issue.message||i18n.t('pdf_corpus.source_issue_default','The extracted source may not be reliable enough for automatic scholarly interpretation.'))}}</p><small v-if="issue.micro_line_ratio!==undefined">{{i18n.t('pdf_corpus.fragmentation_ratio','Micro-line ratio')}}: {{Math.round(Number(issue.micro_line_ratio||0)*100)}}%</small></article></section></template>
<style scoped>.source-issues{display:grid;gap:10px;padding:12px;border:1px solid #d0a84b;border-radius:10px;background:#fff8e9;color:#5d4300}.source-issues[data-resolved="true"]{border-color:#9bc7a9;background:#edf8f1;color:#285c39}.source-issues header div{display:grid;gap:3px}.source-issues header b{font-size:14px}.source-issues header span,.source-issues p,.source-issues small{font-size:.8125rem;line-height:1.5}.source-issues article{display:grid;gap:4px;padding-top:9px;border-top:1px solid color-mix(in srgb,currentColor 18%,transparent)}.source-issues article>div{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.source-issues strong{font-size:13px}.severity{font-weight:800;text-transform:capitalize}.source-issues p{margin:0}.source-issues small{opacity:.82}</style>
