import type { Meta, StoryObj } from "@storybook/vue3-vite";
import CorpusWorkflowStepper from "./CorpusWorkflowStepper.vue";
const meta={title:"PDF Corpus Builder/Workflow Stepper",component:CorpusWorkflowStepper,args:{hasAsset:true,hasManifest:true,stage:"enriching",status:"running",recordCount:84,acceptedCount:0}} satisfies Meta<typeof CorpusWorkflowStepper>;
export default meta;
type Story=StoryObj<typeof meta>;
export const DocumentReview:Story={args:{stage:"document_review",status:"awaiting_manifest_review",hasAsset:true,hasManifest:true}};
export const Enriching:Story={};
export const Review:Story={args:{stage:"review",status:"awaiting_review",acceptedCount:37}};
export const Ready:Story={args:{stage:"ready",status:"ready",acceptedCount:84}};
export const Published:Story={args:{stage:"published",status:"published",acceptedCount:84}};
