<script setup lang="ts">
import { computed } from 'vue';
import { useI18nStore } from '../stores/i18n';
import type { CorpusBuild } from '../api/pdfCorpus';
const props=defineProps<{build:CorpusBuild;disabled?:boolean}>();
const emit=defineEmits<{cancel:[]}>();
const i18n=useI18nStore();
const stage=computed(()=>String(props.build.stage||''));
const stages=['structure','segmenting','constructing_records'];
const currentIndex=computed(()=>stage.value==='reconciling'?stages.indexOf('constructing_records'):Math.max(0,stages.indexOf(stage.value)));
function state(index:number){return index<currentIndex.value?'complete':index===currentIndex.value?'current':'upcoming'}
function label(name:string){return i18n.t(`pdf_corpus.stage.${name}`,name.replace(/_/g,' '))}
</script>
<template><Teleport to="body"><div class="init-backdrop"><section class="init-dialog" role="dialog" aria-modal="true" aria-labelledby="corpus-init-title" aria-describedby="corpus-init-help"><span class="eyebrow">{{i18n.t('pdf_corpus.initializing_workspace','Preparing record workspace')}}</span><h2 id="corpus-init-title">{{i18n.t('pdf_corpus.initialization_title','Building the editable corpus foundation')}}</h2><p id="corpus-init-help">{{i18n.t('pdf_corpus.initialization_help','DerridAI is extracting document structure and finalizing record boundaries. As soon as segmentation is persisted, this window closes and the record-review workspace opens while metadata enrichment continues in the background.')}}</p><ol><li v-for="(name,index) in stages" :key="name" :data-state="state(index)"><span aria-hidden="true">{{state(index)==='complete'?'✓':index+1}}</span><div><b>{{label(name)}}</b><small>{{state(index)==='complete'?i18n.t('pdf_corpus.workflow.complete','Complete'):state(index)==='current'?i18n.t('pdf_corpus.workflow.current','Current'):i18n.t('pdf_corpus.workflow.upcoming','Upcoming')}}</small></div></li></ol><div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" :aria-valuenow="Math.round(Number(build.progress||0)*100)"><span :style="{width:`${Math.round(Number(build.progress||0)*100)}%`}"></span></div><footer><div><b>{{build.source_filename}}</b><span>{{Math.round(Number(build.progress||0)*100)}}% · {{label(stage)}}</span></div><button type="button" class="btn" :disabled="disabled" @click="emit('cancel')">{{i18n.t('pdf_corpus.cancel_build','Cancel build')}}</button></footer></section></div></Teleport></template>
<style scoped>.init-backdrop{position:fixed;inset:0;z-index:30000;display:grid;place-items:center;padding:24px;background:rgba(15,23,42,.76);backdrop-filter:blur(8px)}.init-dialog{width:min(680px,calc(100vw - 32px));display:grid;gap:16px;padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--bg);color:var(--text);box-shadow:0 28px 100px rgba(0,0,0,.42)}.eyebrow{font-size:.8125rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:800}h2{margin:0;font-size:1.35rem}p{margin:0;color:var(--muted);font-size:.9375rem;line-height:1.6}ol{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}li{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid var(--line);border-radius:10px;color:var(--muted)}li[data-state="current"]{border-color:var(--accent);background:var(--soft);color:var(--text)}li[data-state="complete"]{color:var(--text)}li>span{display:grid;place-items:center;width:28px;height:28px;border:1px solid currentColor;border-radius:50%;font-weight:800}li div{display:grid;gap:2px}li b{font-size:.875rem}li small{font-size:.8125rem}.progress{height:9px;overflow:hidden;border-radius:999px;background:var(--soft)}.progress span{display:block;height:100%;background:var(--accent);transition:width .2s}footer{display:flex;justify-content:space-between;align-items:center;gap:16px;padding-top:4px}footer>div{display:grid;gap:2px}footer b{font-size:.875rem}footer span{font-size:.8125rem;color:var(--muted)}@media(max-width:620px){ol{grid-template-columns:1fr}.init-dialog{padding:18px}footer{align-items:stretch;flex-direction:column}}@media(prefers-reduced-motion:reduce){.progress span{transition:none}}</style>
