<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from "vue";
import { useI18nStore } from "../stores/i18n";
import type { CorpusRecord, SourceBlock } from "../api/pdfCorpus";
import PdfEvidenceViewer from "./PdfEvidenceViewer.vue";
const props=defineProps<{record:CorpusRecord;pdfUrl:string;page:number;pageWidth?:number;pageHeight?:number;blocks?:SourceBlock[];busy?:boolean;canMergePrevious?:boolean;canMergeNext?:boolean}>();
const emit=defineEmits<{close:[];accept:[];reject:[];skip:[];undo:[];merge:[direction:"previous"|"next"]}>(); const i18n=useI18nStore(); const dialog=ref<HTMLElement|null>(null);
const state=computed(()=>props.record.review_disposition|| (props.record.accepted?"accepted":props.record.rejected?"rejected":"pending"));
function handleKeydown(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();emit("close");return}if(event.key!=="Tab"||!dialog.value)return;const nodes=Array.from(dialog.value.querySelectorAll<HTMLElement>('button:not([disabled]),[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(node=>node.offsetParent!==null);if(nodes.length<2)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
onMounted(()=>void nextTick(()=>dialog.value?.focus()));
</script>
<template><section ref="dialog" tabindex="-1" class="focus-review" role="dialog" @keydown="handleKeydown" aria-modal="true" :aria-labelledby="`focus-title-${record.record_id}`"><header><div><span class="eyebrow">{{i18n.t('pdf_corpus.focus_view','Focus view')}}</span><h2 :id="`focus-title-${record.record_id}`">{{record.record_id}}</h2><p>{{record.review_reason||i18n.t('pdf_corpus.ready_acceptance','Ready for acceptance')}}</p></div><button class="btn" type="button" @click="emit('close')">{{i18n.t('ui.close','Close')}}</button></header><div class="focus-grid"><div class="focus-source"><PdfEvidenceViewer :pdf-url="pdfUrl" :page="page" :page-width="pageWidth||0" :page-height="pageHeight||0" :blocks="blocks||[]" :evidence-block-ids="[]" /></div><article class="focus-record"><div class="focus-meta"><span>{{i18n.t('pdf_corpus.pages','pp.')}} {{record.page_start}}–{{record.page_end}}</span><span>{{record.text_length.toLocaleString()}} {{i18n.t('pdf_corpus.characters','chars')}}</span><strong>{{i18n.t(`pdf_corpus.disposition.${state}`,state)}}</strong></div><div class="focus-text">{{record.text}}</div><footer><button class="btn" type="button" @click="emit('merge','previous')" :disabled="busy||!canMergePrevious">{{i18n.t('pdf_corpus.merge_previous','Merge previous')}}</button><button class="btn" type="button" @click="emit('merge','next')" :disabled="busy||!canMergeNext">{{i18n.t('pdf_corpus.merge_next','Merge next')}}</button><button class="btn" type="button" @click="emit('undo')" :disabled="busy">{{i18n.t('pdf_corpus.undo','Undo')}}</button><span class="spacer"></span><button class="btn" type="button" @click="emit('skip')" :disabled="busy">{{i18n.t('pdf_corpus.skip','Skip')}}</button><button class="btn danger" type="button" @click="emit('reject')" :disabled="busy">{{i18n.t('pdf_corpus.reject','Reject')}}</button><button class="btn primary" type="button" @click="emit('accept')" :disabled="busy">{{i18n.t('pdf_corpus.accept','Accept')}}</button></footer></article></div></section></template>
<style scoped>.focus-review{position:fixed;inset:18px;z-index:80;background:var(--card);border:1px solid var(--line);border-radius:16px;box-shadow:0 18px 70px rgb(0 0 0/.24);display:grid;grid-template-rows:auto 1fr;overflow:hidden}.focus-review>header{display:flex;justify-content:space-between;gap:20px;padding:14px 16px;border-bottom:1px solid var(--line)}h2{margin:2px 0;font-size:18px}p{margin:0;font-size:10px;color:var(--muted)}.eyebrow{font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.focus-grid{min-height:0;display:grid;grid-template-columns:minmax(420px,1.1fr) minmax(420px,1fr)}.focus-source,.focus-record{min-width:0;overflow:auto}.focus-source{border-inline-end:1px solid var(--line)}.focus-record{display:grid;grid-template-rows:auto 1fr auto}.focus-meta{display:flex;gap:12px;align-items:center;padding:10px 14px;border-bottom:1px solid var(--line);font-size:10px;color:var(--muted)}.focus-text{padding:22px 24px;white-space:pre-wrap;font:16px/1.65 Georgia,serif;max-width:78ch}.focus-record footer{position:sticky;bottom:0;display:flex;gap:8px;align-items:center;padding:12px 14px;border-top:1px solid var(--line);background:var(--card)}.spacer{flex:1}.danger{border-color:#a13f3f;color:#7d2222}@media(max-width:900px){.focus-review{inset:8px}.focus-grid{grid-template-columns:1fr}.focus-source{border-inline-end:0;border-bottom:1px solid var(--line);max-height:45vh}.focus-text{font-size:15px}}@media(prefers-reduced-motion:reduce){.focus-review{scroll-behavior:auto}}</style>
