<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import PdfEvidenceViewer from './PdfEvidenceViewer.vue';
import PdfPageLabelEditor from './PdfPageLabelEditor.vue';
import { useI18nStore } from '../stores/i18n';
import type { DocumentLayoutPlan, PdfAsset, SourceBlock } from '../api/pdfCorpus';
const props=defineProps<{asset:PdfAsset;pdfUrl:string;blocks?:SourceBlock[];disabled?:boolean}>();
const emit=defineEmits<{save:[plan:DocumentLayoutPlan];savePageLabels:[labels:Record<number,string|null>];pageChange:[page:number]}>();
const i18n=useI18nStore(); const current=ref(1); const draft=ref<DocumentLayoutPlan>({page_layout:'single',reading_order:'left_to_right',thread_mode:'continuous'});
watch(()=>props.asset.document_layout,plan=>{draft.value={page_layout:'single',reading_order:'left_to_right',thread_mode:'continuous',...(plan||{}) as DocumentLayoutPlan}},{immediate:true,deep:true});
const pageInfo=computed(()=>props.asset.pages?.find(p=>p.pdf_page===current.value));
const logicalPreview=computed(()=>pageInfo.value?.logical_pages||[]);
function setPage(value:number){current.value=Math.max(1,Math.min(props.asset.page_count||1,value));emit('pageChange',current.value)}
function save(){emit('save',{...draft.value})}
</script>
<template><section class="structure-config" aria-labelledby="document-structure-title"><header><div><span class="eyebrow">{{i18n.t('pdf_corpus.document_structure','Document structure & pagination')}}</span><h3 id="document-structure-title">{{asset.filename}}</h3><p>{{i18n.t('pdf_corpus.document_structure_help','Describe physical page layout and a few reliable anchors. DerridAI derives printed-page labels, structural regions, and thread hints deterministically before asking an LLM to interpret records.')}}</p></div><button class="btn primary" type="button" :disabled="disabled" @click="save">{{i18n.t('pdf_corpus.save_structure','Save structure')}}</button></header>
<div class="structure-grid"><section class="browser"><div class="page-nav"><button class="btn small" type="button" :disabled="current<=1" @click="setPage(current-1)">← {{i18n.t('ui.previous','Previous')}}</button><label><span class="sr-only">{{i18n.t('pdf_corpus.physical_pdf_page','Physical PDF page')}}</span><input class="control compact" type="number" min="1" :max="asset.page_count" :value="current" @change="setPage(Number(($event.target as HTMLInputElement).value))"></label><span>/ {{asset.page_count}}</span><button class="btn small" type="button" :disabled="current>=asset.page_count" @click="setPage(current+1)">{{i18n.t('ui.next','Next')}} →</button></div><PdfEvidenceViewer :pdf-url="pdfUrl" :page="current" :page-width="pageInfo?.width||0" :page-height="pageInfo?.height||0" :blocks="blocks||[]"/><div v-if="draft.page_layout==='two_up'" class="two-up-preview" aria-label="Two-up logical page preview"><span v-for="item in logicalPreview.length?logicalPreview:[{slot:'left'},{slot:'right'}]" :key="item.slot"><b>{{item.slot}}</b><small>{{item.printed_page_label?i18n.tf('pdf_corpus.printed_page_value','printed p. {page}',{page:item.printed_page_label}):i18n.t('pdf_corpus.not_mapped_yet','not mapped yet')}}</small></span></div></section>
<section class="rules"><fieldset><legend>{{i18n.t('pdf_corpus.page_layout','Page layout')}}</legend><label><input v-model="draft.page_layout" type="radio" value="single"> {{i18n.t('pdf_corpus.single_page_layout','1 printed page per PDF page')}}</label><label><input v-model="draft.page_layout" type="radio" value="two_up"> {{i18n.t('pdf_corpus.two_up_layout','2 printed pages per PDF page')}}</label><label v-if="draft.page_layout==='two_up'"><span>{{i18n.t('pdf_corpus.reading_order','Reading order')}}</span><select v-model="draft.reading_order" class="control"><option value="left_to_right">{{i18n.t('pdf_corpus.left_to_right','Left → right')}}</option><option value="right_to_left">{{i18n.t('pdf_corpus.right_to_left','Right → left')}}</option></select></label></fieldset>
<fieldset><legend>{{i18n.t('pdf_corpus.structural_anchors','Structural anchors')}}</legend><label><span>{{i18n.t('pdf_corpus.main_text_starts_pdf','First main-text page appears on PDF page')}}</span><div class="anchor"><input v-model.number="draft.main_text_pdf_start" class="control" type="number" min="1" :max="asset.page_count"><button class="btn small" type="button" @click="draft.main_text_pdf_start=current">{{i18n.t('pdf_corpus.use_current_page','Use current')}}</button></div></label><label><span>{{i18n.t('pdf_corpus.first_printed_page_number','Printed page number at main-text start')}}</span><input v-model.number="draft.main_text_printed_start" class="control" type="number" min="1"></label><label v-if="draft.page_layout==='two_up'"><span>{{i18n.t('pdf_corpus.main_text_slot','Main text begins on')}}</span><select v-model="draft.main_text_slot" class="control"><option value="left">{{i18n.t('pdf_corpus.left_page','Left page')}}</option><option value="right">{{i18n.t('pdf_corpus.right_page','Right page')}}</option></select></label><label><span>{{i18n.t('pdf_corpus.bibliography_starts_pdf','Bibliography begins on PDF page')}}</span><div class="anchor"><input v-model.number="draft.bibliography_pdf_start" class="control" type="number" min="1" :max="asset.page_count"><button class="btn small" type="button" @click="draft.bibliography_pdf_start=current">{{i18n.t('pdf_corpus.use_current_page','Use current')}}</button></div></label></fieldset>
<fieldset><legend>{{i18n.t('pdf_corpus.page_threads','Page threads')}}</legend><label><span>{{i18n.t('pdf_corpus.thread_pattern','Thread pattern')}}</span><select v-model="draft.thread_mode" class="control"><option value="continuous">{{i18n.t('pdf_corpus.thread_continuous','Single continuous sequence')}}</option><option value="odd_even">{{i18n.t('pdf_corpus.thread_odd_even','Odd PDF pages = A; even = B')}}</option><option value="even_odd">{{i18n.t('pdf_corpus.thread_even_odd','Even PDF pages = A; odd = B')}}</option><option value="left_right" :disabled="draft.page_layout!=='two_up'">{{i18n.t('pdf_corpus.thread_left_right','Left logical pages = A; right = B')}}</option><option value="right_left" :disabled="draft.page_layout!=='two_up'">{{i18n.t('pdf_corpus.thread_right_left','Right logical pages = A; left = B')}}</option></select></label><div v-if="draft.thread_mode!=='continuous'" class="thread-languages"><label><span>{{i18n.t('pdf_corpus.thread_a_language','Thread A language (optional)')}}</span><input v-model="draft.thread_a_language" class="control" placeholder="en_us"></label><label><span>{{i18n.t('pdf_corpus.thread_b_language','Thread B language (optional)')}}</span><input v-model="draft.thread_b_language" class="control" placeholder="fr_fr"></label></div></fieldset></section></div>
<details class="exceptions"><summary>{{i18n.t('pdf_corpus.mapping_exceptions','Review generated mapping / exceptions')}}</summary><p>{{i18n.t('pdf_corpus.mapping_exceptions_help','Use per-page overrides only for exceptions. Deterministic rules remain the default mapping source.')}}</p><PdfPageLabelEditor :pages="asset.pages||[]" :disabled="disabled" @save="labels=>emit('savePageLabels',labels)"/></details></section></template>
<style scoped>.structure-config{display:grid;gap:14px;padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--card)}.structure-config>header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.structure-config h3{margin:2px 0;font-size:1rem}.structure-config header p,.exceptions>p{margin:4px 0 0;max-width:78ch;color:var(--muted);font-size:.875rem;line-height:1.45}.eyebrow{font-size:.75rem;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);font-weight:800}.structure-grid{display:grid;grid-template-columns:minmax(360px,1.2fr) minmax(330px,.8fr);gap:14px}.browser,.rules fieldset{min-width:0;border:1px solid var(--line);border-radius:10px;background:var(--soft)}.browser{overflow:hidden}.page-nav{display:flex;gap:7px;align-items:center;padding:9px;border-bottom:1px solid var(--line);background:var(--card)}.page-nav input{width:76px}.rules{display:grid;gap:10px;align-content:start}.rules fieldset{display:grid;gap:9px;margin:0;padding:11px}.rules legend{padding:0 4px;font-size:.875rem;font-weight:800}.rules label{display:grid;gap:5px;font-size:.8125rem;line-height:1.4}.rules label:has(input[type=radio]){display:flex;align-items:flex-start}.rules input[type=radio]{inline-size:18px;block-size:18px;flex:none}.anchor{display:grid;grid-template-columns:1fr auto;gap:7px}.thread-languages{display:grid;grid-template-columns:1fr 1fr;gap:8px}.two-up-preview{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid var(--line);background:var(--card)}.two-up-preview span{display:grid;gap:2px;padding:8px 10px;border-inline-end:1px solid var(--line)}.two-up-preview small{color:var(--muted)}.exceptions summary{min-height:40px;display:flex;align-items:center;font-weight:800;cursor:pointer}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.structure-config :is(input,select,button,summary):focus-visible{outline:3px solid var(--accent);outline-offset:2px}@media(max-width:900px){.structure-grid{grid-template-columns:1fr}.structure-config>header{flex-direction:column}.thread-languages{grid-template-columns:1fr}}</style>
