/*
 * This file is part of DerridAI, a cELF-compliant research workspace
 * Copyright © 2026  Aaron John Schlosser, PhD
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import js from "@eslint/js";
import ts from "typescript-eslint";
import vue from "eslint-plugin-vue";
import globals from "globals";

export default ts.config(
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "sdk/dist/**",
      "storybook-static/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by `npm run codegen`; its freshness is checked by `npm run codegen:check`.
      "src/api/graphql/generated.ts",
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...vue.configs["flat/essential"],
  {
    files: ["**/*.{js,mjs,ts,vue}"],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // UI component filenames are existing public imports; naming changes add no safety.
      "vue/multi-word-component-names": "off",
      "@typescript-eslint/no-unused-expressions": [
        "error",
        { allowShortCircuit: true, allowTernary: true },
      ],
    },
  },
  {
    files: ["**/*.vue"],
    rules: { "no-undef": "off" },
    languageOptions: { parserOptions: { parser: ts.parser, extraFileExtensions: [".vue"] } },
  },
  {
    files: ["tests/**/*.{js,ts}"],
    // Tests intentionally use broad fixture doubles and Playwright's empty fixture
    // destructuring. Keep real hygiene rules (unused symbols, undefined names, etc.)
    // while allowing these test-specific patterns.
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-empty-pattern": "off",
    },
  },
);
